// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GoogleApiKey is the predicate function for googleapikey builders.
type GoogleApiKey func(*sql.Selector)

// SystemUser is the predicate function for systemuser builders.
type SystemUser func(*sql.Selector)
