version: "3"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - database.env
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "40000:40000"
    env_file:
      - development.env
    links:
      - postgres
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/usr/src/app"
    command:
      - yarn
      - dev
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    volumes:
      - "./nginx_dev.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"