FROM golang:1.19.3 AS builder

RUN go install github.com/go-delve/delve/cmd/dlv@latest

ADD . /src
WORKDIR /src

RUN go build -o main

FROM debian:buster

RUN apt update && apt install -y ca-certificates

WORKDIR /src
COPY --from=builder /go/bin/dlv /
COPY --from=builder /src /

EXPOSE 8000 40000
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/main"]
