// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bear-san/googlechat-sender/backend/ent/googleapikey"
	"github.com/bear-san/googlechat-sender/backend/ent/predicate"
)

// GoogleApiKeyQuery is the builder for querying GoogleApiKey entities.
type GoogleApiKeyQuery struct {
	config
	ctx        *QueryContext
	order      []googleapikey.OrderOption
	inters     []Interceptor
	predicates []predicate.GoogleApiKey
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoogleApiKeyQuery builder.
func (gakq *GoogleApiKeyQuery) Where(ps ...predicate.GoogleApiKey) *GoogleApiKeyQuery {
	gakq.predicates = append(gakq.predicates, ps...)
	return gakq
}

// Limit the number of records to be returned by this query.
func (gakq *GoogleApiKeyQuery) Limit(limit int) *GoogleApiKeyQuery {
	gakq.ctx.Limit = &limit
	return gakq
}

// Offset to start from.
func (gakq *GoogleApiKeyQuery) Offset(offset int) *GoogleApiKeyQuery {
	gakq.ctx.Offset = &offset
	return gakq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gakq *GoogleApiKeyQuery) Unique(unique bool) *GoogleApiKeyQuery {
	gakq.ctx.Unique = &unique
	return gakq
}

// Order specifies how the records should be ordered.
func (gakq *GoogleApiKeyQuery) Order(o ...googleapikey.OrderOption) *GoogleApiKeyQuery {
	gakq.order = append(gakq.order, o...)
	return gakq
}

// First returns the first GoogleApiKey entity from the query.
// Returns a *NotFoundError when no GoogleApiKey was found.
func (gakq *GoogleApiKeyQuery) First(ctx context.Context) (*GoogleApiKey, error) {
	nodes, err := gakq.Limit(1).All(setContextOp(ctx, gakq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{googleapikey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) FirstX(ctx context.Context) *GoogleApiKey {
	node, err := gakq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoogleApiKey ID from the query.
// Returns a *NotFoundError when no GoogleApiKey ID was found.
func (gakq *GoogleApiKeyQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = gakq.Limit(1).IDs(setContextOp(ctx, gakq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{googleapikey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) FirstIDX(ctx context.Context) string {
	id, err := gakq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoogleApiKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GoogleApiKey entity is found.
// Returns a *NotFoundError when no GoogleApiKey entities are found.
func (gakq *GoogleApiKeyQuery) Only(ctx context.Context) (*GoogleApiKey, error) {
	nodes, err := gakq.Limit(2).All(setContextOp(ctx, gakq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{googleapikey.Label}
	default:
		return nil, &NotSingularError{googleapikey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) OnlyX(ctx context.Context) *GoogleApiKey {
	node, err := gakq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoogleApiKey ID in the query.
// Returns a *NotSingularError when more than one GoogleApiKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (gakq *GoogleApiKeyQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = gakq.Limit(2).IDs(setContextOp(ctx, gakq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{googleapikey.Label}
	default:
		err = &NotSingularError{googleapikey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) OnlyIDX(ctx context.Context) string {
	id, err := gakq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoogleApiKeys.
func (gakq *GoogleApiKeyQuery) All(ctx context.Context) ([]*GoogleApiKey, error) {
	ctx = setContextOp(ctx, gakq.ctx, "All")
	if err := gakq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GoogleApiKey, *GoogleApiKeyQuery]()
	return withInterceptors[[]*GoogleApiKey](ctx, gakq, qr, gakq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) AllX(ctx context.Context) []*GoogleApiKey {
	nodes, err := gakq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoogleApiKey IDs.
func (gakq *GoogleApiKeyQuery) IDs(ctx context.Context) (ids []string, err error) {
	if gakq.ctx.Unique == nil && gakq.path != nil {
		gakq.Unique(true)
	}
	ctx = setContextOp(ctx, gakq.ctx, "IDs")
	if err = gakq.Select(googleapikey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) IDsX(ctx context.Context) []string {
	ids, err := gakq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gakq *GoogleApiKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gakq.ctx, "Count")
	if err := gakq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gakq, querierCount[*GoogleApiKeyQuery](), gakq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) CountX(ctx context.Context) int {
	count, err := gakq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gakq *GoogleApiKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gakq.ctx, "Exist")
	switch _, err := gakq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gakq *GoogleApiKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := gakq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoogleApiKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gakq *GoogleApiKeyQuery) Clone() *GoogleApiKeyQuery {
	if gakq == nil {
		return nil
	}
	return &GoogleApiKeyQuery{
		config:     gakq.config,
		ctx:        gakq.ctx.Clone(),
		order:      append([]googleapikey.OrderOption{}, gakq.order...),
		inters:     append([]Interceptor{}, gakq.inters...),
		predicates: append([]predicate.GoogleApiKey{}, gakq.predicates...),
		// clone intermediate query.
		sql:  gakq.sql.Clone(),
		path: gakq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccessToken string `json:"access_token,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoogleApiKey.Query().
//		GroupBy(googleapikey.FieldAccessToken).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gakq *GoogleApiKeyQuery) GroupBy(field string, fields ...string) *GoogleApiKeyGroupBy {
	gakq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoogleApiKeyGroupBy{build: gakq}
	grbuild.flds = &gakq.ctx.Fields
	grbuild.label = googleapikey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccessToken string `json:"access_token,omitempty"`
//	}
//
//	client.GoogleApiKey.Query().
//		Select(googleapikey.FieldAccessToken).
//		Scan(ctx, &v)
func (gakq *GoogleApiKeyQuery) Select(fields ...string) *GoogleApiKeySelect {
	gakq.ctx.Fields = append(gakq.ctx.Fields, fields...)
	sbuild := &GoogleApiKeySelect{GoogleApiKeyQuery: gakq}
	sbuild.label = googleapikey.Label
	sbuild.flds, sbuild.scan = &gakq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoogleApiKeySelect configured with the given aggregations.
func (gakq *GoogleApiKeyQuery) Aggregate(fns ...AggregateFunc) *GoogleApiKeySelect {
	return gakq.Select().Aggregate(fns...)
}

func (gakq *GoogleApiKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gakq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gakq); err != nil {
				return err
			}
		}
	}
	for _, f := range gakq.ctx.Fields {
		if !googleapikey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gakq.path != nil {
		prev, err := gakq.path(ctx)
		if err != nil {
			return err
		}
		gakq.sql = prev
	}
	return nil
}

func (gakq *GoogleApiKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GoogleApiKey, error) {
	var (
		nodes = []*GoogleApiKey{}
		_spec = gakq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GoogleApiKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GoogleApiKey{config: gakq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gakq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gakq *GoogleApiKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gakq.querySpec()
	_spec.Node.Columns = gakq.ctx.Fields
	if len(gakq.ctx.Fields) > 0 {
		_spec.Unique = gakq.ctx.Unique != nil && *gakq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gakq.driver, _spec)
}

func (gakq *GoogleApiKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(googleapikey.Table, googleapikey.Columns, sqlgraph.NewFieldSpec(googleapikey.FieldID, field.TypeString))
	_spec.From = gakq.sql
	if unique := gakq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gakq.path != nil {
		_spec.Unique = true
	}
	if fields := gakq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, googleapikey.FieldID)
		for i := range fields {
			if fields[i] != googleapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gakq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gakq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gakq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gakq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gakq *GoogleApiKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gakq.driver.Dialect())
	t1 := builder.Table(googleapikey.Table)
	columns := gakq.ctx.Fields
	if len(columns) == 0 {
		columns = googleapikey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gakq.sql != nil {
		selector = gakq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gakq.ctx.Unique != nil && *gakq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gakq.predicates {
		p(selector)
	}
	for _, p := range gakq.order {
		p(selector)
	}
	if offset := gakq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gakq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoogleApiKeyGroupBy is the group-by builder for GoogleApiKey entities.
type GoogleApiKeyGroupBy struct {
	selector
	build *GoogleApiKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gakgb *GoogleApiKeyGroupBy) Aggregate(fns ...AggregateFunc) *GoogleApiKeyGroupBy {
	gakgb.fns = append(gakgb.fns, fns...)
	return gakgb
}

// Scan applies the selector query and scans the result into the given value.
func (gakgb *GoogleApiKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gakgb.build.ctx, "GroupBy")
	if err := gakgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoogleApiKeyQuery, *GoogleApiKeyGroupBy](ctx, gakgb.build, gakgb, gakgb.build.inters, v)
}

func (gakgb *GoogleApiKeyGroupBy) sqlScan(ctx context.Context, root *GoogleApiKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gakgb.fns))
	for _, fn := range gakgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gakgb.flds)+len(gakgb.fns))
		for _, f := range *gakgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gakgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gakgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoogleApiKeySelect is the builder for selecting fields of GoogleApiKey entities.
type GoogleApiKeySelect struct {
	*GoogleApiKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gaks *GoogleApiKeySelect) Aggregate(fns ...AggregateFunc) *GoogleApiKeySelect {
	gaks.fns = append(gaks.fns, fns...)
	return gaks
}

// Scan applies the selector query and scans the result into the given value.
func (gaks *GoogleApiKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gaks.ctx, "Select")
	if err := gaks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoogleApiKeyQuery, *GoogleApiKeySelect](ctx, gaks.GoogleApiKeyQuery, gaks, gaks.inters, v)
}

func (gaks *GoogleApiKeySelect) sqlScan(ctx context.Context, root *GoogleApiKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gaks.fns))
	for _, fn := range gaks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gaks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gaks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
