// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bear-san/googlechat-sender/backend/ent/postschedule"
	"github.com/bear-san/googlechat-sender/backend/ent/predicate"
)

// PostScheduleDelete is the builder for deleting a PostSchedule entity.
type PostScheduleDelete struct {
	config
	hooks    []Hook
	mutation *PostScheduleMutation
}

// Where appends a list predicates to the PostScheduleDelete builder.
func (psd *PostScheduleDelete) Where(ps ...predicate.PostSchedule) *PostScheduleDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PostScheduleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, PostScheduleMutation](ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PostScheduleDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PostScheduleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postschedule.Table, sqlgraph.NewFieldSpec(postschedule.FieldID, field.TypeUUID))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PostScheduleDeleteOne is the builder for deleting a single PostSchedule entity.
type PostScheduleDeleteOne struct {
	psd *PostScheduleDelete
}

// Where appends a list predicates to the PostScheduleDelete builder.
func (psdo *PostScheduleDeleteOne) Where(ps ...predicate.PostSchedule) *PostScheduleDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PostScheduleDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postschedule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PostScheduleDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
