// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bear-san/googlechat-sender/backend/ent/postschedule"
	"github.com/bear-san/googlechat-sender/backend/ent/predicate"
)

// PostScheduleUpdate is the builder for updating PostSchedule entities.
type PostScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *PostScheduleMutation
}

// Where appends a list predicates to the PostScheduleUpdate builder.
func (psu *PostScheduleUpdate) Where(ps ...predicate.PostSchedule) *PostScheduleUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// SetUID sets the "uid" field.
func (psu *PostScheduleUpdate) SetUID(s string) *PostScheduleUpdate {
	psu.mutation.SetUID(s)
	return psu
}

// SetTarget sets the "target" field.
func (psu *PostScheduleUpdate) SetTarget(s string) *PostScheduleUpdate {
	psu.mutation.SetTarget(s)
	return psu
}

// SetDisplayName sets the "displayName" field.
func (psu *PostScheduleUpdate) SetDisplayName(s string) *PostScheduleUpdate {
	psu.mutation.SetDisplayName(s)
	return psu
}

// SetText sets the "text" field.
func (psu *PostScheduleUpdate) SetText(s string) *PostScheduleUpdate {
	psu.mutation.SetText(s)
	return psu
}

// SetIsSent sets the "is_sent" field.
func (psu *PostScheduleUpdate) SetIsSent(b bool) *PostScheduleUpdate {
	psu.mutation.SetIsSent(b)
	return psu
}

// SetSendAt sets the "send_at" field.
func (psu *PostScheduleUpdate) SetSendAt(t time.Time) *PostScheduleUpdate {
	psu.mutation.SetSendAt(t)
	return psu
}

// Mutation returns the PostScheduleMutation object of the builder.
func (psu *PostScheduleUpdate) Mutation() *PostScheduleMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *PostScheduleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, PostScheduleMutation](ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *PostScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *PostScheduleUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *PostScheduleUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psu *PostScheduleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(postschedule.Table, postschedule.Columns, sqlgraph.NewFieldSpec(postschedule.FieldID, field.TypeUUID))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psu.mutation.UID(); ok {
		_spec.SetField(postschedule.FieldUID, field.TypeString, value)
	}
	if value, ok := psu.mutation.Target(); ok {
		_spec.SetField(postschedule.FieldTarget, field.TypeString, value)
	}
	if value, ok := psu.mutation.DisplayName(); ok {
		_spec.SetField(postschedule.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := psu.mutation.Text(); ok {
		_spec.SetField(postschedule.FieldText, field.TypeString, value)
	}
	if value, ok := psu.mutation.IsSent(); ok {
		_spec.SetField(postschedule.FieldIsSent, field.TypeBool, value)
	}
	if value, ok := psu.mutation.SendAt(); ok {
		_spec.SetField(postschedule.FieldSendAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// PostScheduleUpdateOne is the builder for updating a single PostSchedule entity.
type PostScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostScheduleMutation
}

// SetUID sets the "uid" field.
func (psuo *PostScheduleUpdateOne) SetUID(s string) *PostScheduleUpdateOne {
	psuo.mutation.SetUID(s)
	return psuo
}

// SetTarget sets the "target" field.
func (psuo *PostScheduleUpdateOne) SetTarget(s string) *PostScheduleUpdateOne {
	psuo.mutation.SetTarget(s)
	return psuo
}

// SetDisplayName sets the "displayName" field.
func (psuo *PostScheduleUpdateOne) SetDisplayName(s string) *PostScheduleUpdateOne {
	psuo.mutation.SetDisplayName(s)
	return psuo
}

// SetText sets the "text" field.
func (psuo *PostScheduleUpdateOne) SetText(s string) *PostScheduleUpdateOne {
	psuo.mutation.SetText(s)
	return psuo
}

// SetIsSent sets the "is_sent" field.
func (psuo *PostScheduleUpdateOne) SetIsSent(b bool) *PostScheduleUpdateOne {
	psuo.mutation.SetIsSent(b)
	return psuo
}

// SetSendAt sets the "send_at" field.
func (psuo *PostScheduleUpdateOne) SetSendAt(t time.Time) *PostScheduleUpdateOne {
	psuo.mutation.SetSendAt(t)
	return psuo
}

// Mutation returns the PostScheduleMutation object of the builder.
func (psuo *PostScheduleUpdateOne) Mutation() *PostScheduleMutation {
	return psuo.mutation
}

// Where appends a list predicates to the PostScheduleUpdate builder.
func (psuo *PostScheduleUpdateOne) Where(ps ...predicate.PostSchedule) *PostScheduleUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *PostScheduleUpdateOne) Select(field string, fields ...string) *PostScheduleUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated PostSchedule entity.
func (psuo *PostScheduleUpdateOne) Save(ctx context.Context) (*PostSchedule, error) {
	return withHooks[*PostSchedule, PostScheduleMutation](ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *PostScheduleUpdateOne) SaveX(ctx context.Context) *PostSchedule {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *PostScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *PostScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psuo *PostScheduleUpdateOne) sqlSave(ctx context.Context) (_node *PostSchedule, err error) {
	_spec := sqlgraph.NewUpdateSpec(postschedule.Table, postschedule.Columns, sqlgraph.NewFieldSpec(postschedule.FieldID, field.TypeUUID))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostSchedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postschedule.FieldID)
		for _, f := range fields {
			if !postschedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postschedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := psuo.mutation.UID(); ok {
		_spec.SetField(postschedule.FieldUID, field.TypeString, value)
	}
	if value, ok := psuo.mutation.Target(); ok {
		_spec.SetField(postschedule.FieldTarget, field.TypeString, value)
	}
	if value, ok := psuo.mutation.DisplayName(); ok {
		_spec.SetField(postschedule.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := psuo.mutation.Text(); ok {
		_spec.SetField(postschedule.FieldText, field.TypeString, value)
	}
	if value, ok := psuo.mutation.IsSent(); ok {
		_spec.SetField(postschedule.FieldIsSent, field.TypeBool, value)
	}
	if value, ok := psuo.mutation.SendAt(); ok {
		_spec.SetField(postschedule.FieldSendAt, field.TypeTime, value)
	}
	_node = &PostSchedule{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
