// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bear-san/googlechat-sender/backend/ent/predicate"
	"github.com/bear-san/googlechat-sender/backend/ent/systemuser"
)

// SystemUserDelete is the builder for deleting a SystemUser entity.
type SystemUserDelete struct {
	config
	hooks    []Hook
	mutation *SystemUserMutation
}

// Where appends a list predicates to the SystemUserDelete builder.
func (sud *SystemUserDelete) Where(ps ...predicate.SystemUser) *SystemUserDelete {
	sud.mutation.Where(ps...)
	return sud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sud *SystemUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, SystemUserMutation](ctx, sud.sqlExec, sud.mutation, sud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sud *SystemUserDelete) ExecX(ctx context.Context) int {
	n, err := sud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sud *SystemUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(systemuser.Table, sqlgraph.NewFieldSpec(systemuser.FieldID, field.TypeString))
	if ps := sud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sud.mutation.done = true
	return affected, err
}

// SystemUserDeleteOne is the builder for deleting a single SystemUser entity.
type SystemUserDeleteOne struct {
	sud *SystemUserDelete
}

// Where appends a list predicates to the SystemUserDelete builder.
func (sudo *SystemUserDeleteOne) Where(ps ...predicate.SystemUser) *SystemUserDeleteOne {
	sudo.sud.mutation.Where(ps...)
	return sudo
}

// Exec executes the deletion query.
func (sudo *SystemUserDeleteOne) Exec(ctx context.Context) error {
	n, err := sudo.sud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{systemuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sudo *SystemUserDeleteOne) ExecX(ctx context.Context) {
	if err := sudo.Exec(ctx); err != nil {
		panic(err)
	}
}
