// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bear-san/googlechat-sender/backend/ent/predicate"
	"github.com/bear-san/googlechat-sender/backend/ent/systemuser"
)

// SystemUserQuery is the builder for querying SystemUser entities.
type SystemUserQuery struct {
	config
	ctx        *QueryContext
	order      []systemuser.OrderOption
	inters     []Interceptor
	predicates []predicate.SystemUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SystemUserQuery builder.
func (suq *SystemUserQuery) Where(ps ...predicate.SystemUser) *SystemUserQuery {
	suq.predicates = append(suq.predicates, ps...)
	return suq
}

// Limit the number of records to be returned by this query.
func (suq *SystemUserQuery) Limit(limit int) *SystemUserQuery {
	suq.ctx.Limit = &limit
	return suq
}

// Offset to start from.
func (suq *SystemUserQuery) Offset(offset int) *SystemUserQuery {
	suq.ctx.Offset = &offset
	return suq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (suq *SystemUserQuery) Unique(unique bool) *SystemUserQuery {
	suq.ctx.Unique = &unique
	return suq
}

// Order specifies how the records should be ordered.
func (suq *SystemUserQuery) Order(o ...systemuser.OrderOption) *SystemUserQuery {
	suq.order = append(suq.order, o...)
	return suq
}

// First returns the first SystemUser entity from the query.
// Returns a *NotFoundError when no SystemUser was found.
func (suq *SystemUserQuery) First(ctx context.Context) (*SystemUser, error) {
	nodes, err := suq.Limit(1).All(setContextOp(ctx, suq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{systemuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (suq *SystemUserQuery) FirstX(ctx context.Context) *SystemUser {
	node, err := suq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SystemUser ID from the query.
// Returns a *NotFoundError when no SystemUser ID was found.
func (suq *SystemUserQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = suq.Limit(1).IDs(setContextOp(ctx, suq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{systemuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (suq *SystemUserQuery) FirstIDX(ctx context.Context) string {
	id, err := suq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SystemUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SystemUser entity is found.
// Returns a *NotFoundError when no SystemUser entities are found.
func (suq *SystemUserQuery) Only(ctx context.Context) (*SystemUser, error) {
	nodes, err := suq.Limit(2).All(setContextOp(ctx, suq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{systemuser.Label}
	default:
		return nil, &NotSingularError{systemuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (suq *SystemUserQuery) OnlyX(ctx context.Context) *SystemUser {
	node, err := suq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SystemUser ID in the query.
// Returns a *NotSingularError when more than one SystemUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (suq *SystemUserQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = suq.Limit(2).IDs(setContextOp(ctx, suq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{systemuser.Label}
	default:
		err = &NotSingularError{systemuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (suq *SystemUserQuery) OnlyIDX(ctx context.Context) string {
	id, err := suq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SystemUsers.
func (suq *SystemUserQuery) All(ctx context.Context) ([]*SystemUser, error) {
	ctx = setContextOp(ctx, suq.ctx, "All")
	if err := suq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SystemUser, *SystemUserQuery]()
	return withInterceptors[[]*SystemUser](ctx, suq, qr, suq.inters)
}

// AllX is like All, but panics if an error occurs.
func (suq *SystemUserQuery) AllX(ctx context.Context) []*SystemUser {
	nodes, err := suq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SystemUser IDs.
func (suq *SystemUserQuery) IDs(ctx context.Context) (ids []string, err error) {
	if suq.ctx.Unique == nil && suq.path != nil {
		suq.Unique(true)
	}
	ctx = setContextOp(ctx, suq.ctx, "IDs")
	if err = suq.Select(systemuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (suq *SystemUserQuery) IDsX(ctx context.Context) []string {
	ids, err := suq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (suq *SystemUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, suq.ctx, "Count")
	if err := suq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, suq, querierCount[*SystemUserQuery](), suq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (suq *SystemUserQuery) CountX(ctx context.Context) int {
	count, err := suq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (suq *SystemUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, suq.ctx, "Exist")
	switch _, err := suq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (suq *SystemUserQuery) ExistX(ctx context.Context) bool {
	exist, err := suq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SystemUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (suq *SystemUserQuery) Clone() *SystemUserQuery {
	if suq == nil {
		return nil
	}
	return &SystemUserQuery{
		config:     suq.config,
		ctx:        suq.ctx.Clone(),
		order:      append([]systemuser.OrderOption{}, suq.order...),
		inters:     append([]Interceptor{}, suq.inters...),
		predicates: append([]predicate.SystemUser{}, suq.predicates...),
		// clone intermediate query.
		sql:  suq.sql.Clone(),
		path: suq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SystemUser.Query().
//		GroupBy(systemuser.FieldEmail).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (suq *SystemUserQuery) GroupBy(field string, fields ...string) *SystemUserGroupBy {
	suq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SystemUserGroupBy{build: suq}
	grbuild.flds = &suq.ctx.Fields
	grbuild.label = systemuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Email string `json:"email,omitempty"`
//	}
//
//	client.SystemUser.Query().
//		Select(systemuser.FieldEmail).
//		Scan(ctx, &v)
func (suq *SystemUserQuery) Select(fields ...string) *SystemUserSelect {
	suq.ctx.Fields = append(suq.ctx.Fields, fields...)
	sbuild := &SystemUserSelect{SystemUserQuery: suq}
	sbuild.label = systemuser.Label
	sbuild.flds, sbuild.scan = &suq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SystemUserSelect configured with the given aggregations.
func (suq *SystemUserQuery) Aggregate(fns ...AggregateFunc) *SystemUserSelect {
	return suq.Select().Aggregate(fns...)
}

func (suq *SystemUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range suq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, suq); err != nil {
				return err
			}
		}
	}
	for _, f := range suq.ctx.Fields {
		if !systemuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if suq.path != nil {
		prev, err := suq.path(ctx)
		if err != nil {
			return err
		}
		suq.sql = prev
	}
	return nil
}

func (suq *SystemUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SystemUser, error) {
	var (
		nodes = []*SystemUser{}
		_spec = suq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SystemUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SystemUser{config: suq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, suq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (suq *SystemUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := suq.querySpec()
	_spec.Node.Columns = suq.ctx.Fields
	if len(suq.ctx.Fields) > 0 {
		_spec.Unique = suq.ctx.Unique != nil && *suq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, suq.driver, _spec)
}

func (suq *SystemUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(systemuser.Table, systemuser.Columns, sqlgraph.NewFieldSpec(systemuser.FieldID, field.TypeString))
	_spec.From = suq.sql
	if unique := suq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if suq.path != nil {
		_spec.Unique = true
	}
	if fields := suq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemuser.FieldID)
		for i := range fields {
			if fields[i] != systemuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := suq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := suq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := suq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := suq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (suq *SystemUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(suq.driver.Dialect())
	t1 := builder.Table(systemuser.Table)
	columns := suq.ctx.Fields
	if len(columns) == 0 {
		columns = systemuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if suq.sql != nil {
		selector = suq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if suq.ctx.Unique != nil && *suq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range suq.predicates {
		p(selector)
	}
	for _, p := range suq.order {
		p(selector)
	}
	if offset := suq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := suq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SystemUserGroupBy is the group-by builder for SystemUser entities.
type SystemUserGroupBy struct {
	selector
	build *SystemUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sugb *SystemUserGroupBy) Aggregate(fns ...AggregateFunc) *SystemUserGroupBy {
	sugb.fns = append(sugb.fns, fns...)
	return sugb
}

// Scan applies the selector query and scans the result into the given value.
func (sugb *SystemUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sugb.build.ctx, "GroupBy")
	if err := sugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemUserQuery, *SystemUserGroupBy](ctx, sugb.build, sugb, sugb.build.inters, v)
}

func (sugb *SystemUserGroupBy) sqlScan(ctx context.Context, root *SystemUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sugb.fns))
	for _, fn := range sugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sugb.flds)+len(sugb.fns))
		for _, f := range *sugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SystemUserSelect is the builder for selecting fields of SystemUser entities.
type SystemUserSelect struct {
	*SystemUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sus *SystemUserSelect) Aggregate(fns ...AggregateFunc) *SystemUserSelect {
	sus.fns = append(sus.fns, fns...)
	return sus
}

// Scan applies the selector query and scans the result into the given value.
func (sus *SystemUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sus.ctx, "Select")
	if err := sus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemUserQuery, *SystemUserSelect](ctx, sus.SystemUserQuery, sus, sus.inters, v)
}

func (sus *SystemUserSelect) sqlScan(ctx context.Context, root *SystemUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sus.fns))
	for _, fn := range sus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
