// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SystemUsersColumns holds the columns for the "system_users" table.
	SystemUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// SystemUsersTable holds the schema information for the "system_users" table.
	SystemUsersTable = &schema.Table{
		Name:       "system_users",
		Columns:    SystemUsersColumns,
		PrimaryKey: []*schema.Column{SystemUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SystemUsersTable,
	}
)

func init() {
}
