// Code generated by ent, DO NOT EDIT.

package postschedule

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the postschedule type in the database.
	Label = "post_schedule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldIsSent holds the string denoting the is_sent field in the database.
	FieldIsSent = "is_sent"
	// FieldSendAt holds the string denoting the send_at field in the database.
	FieldSendAt = "send_at"
	// Table holds the table name of the postschedule in the database.
	Table = "post_schedules"
)

// Columns holds all SQL columns for postschedule fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldTarget,
	FieldText,
	FieldIsSent,
	FieldSendAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PostSchedule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByIsSent orders the results by the is_sent field.
func ByIsSent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSent, opts...).ToFunc()
}

// BySendAt orders the results by the send_at field.
func BySendAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSendAt, opts...).ToFunc()
}
